
name: iOS Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: iOS Build
    permissions: write-all
    runs-on: macos-13
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v3
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Get Libs Hash
        id: get_hash
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          echo "hash=$(haxe -cp commandline -D analyzer-optimize --run Main get-libs-hash)" >> $GITHUB_OUTPUT
      - name: Restore existing build cache for faster compilation
        id: cache
        uses: actions/cache@v3
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: cache-build-ios-${{ steps.get_hash.outputs.hash }}
          path: |
            .haxelib/
            ~/.hxcpp/
            export/release/ios/CodenameEngine/haxe/
            export/release/ios/CodenameEngine/obj/
          restore-keys: |
            cache-build-ios-${{ steps.get_hash.outputs.hash }}
      - name: Enable HXCPP compile cache
        run: |
          echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV
      - name: Installing/Updating libraries
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s --actions
      - name: Building HXCPP
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          haxelib dev hxcpp .haxelib/hxcpp/git
          cd .haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          cd ../../../../..
      - name: Building Lime
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          haxelib dev lime .haxelib/lime/git
          haxelib run lime setup -alias -y -nocffi -eval
          haxelib run lime rebuild ios -release -nocolor -eval
          lime rebuild tools -release -nocolor -eval
      - name: Building the game
        run: |
          haxelib run lime build ios -nosign
      - name: Making app from built payload
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r CodenameEngine.ipa Payload
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4
        with:
          name: Codename Engine
          path: export/release/ios/build/Release-iphoneos/*.ipa
      - name: Clearing already existing cache
        uses: actions/github-script@v6
        env:
          HASH: ${{ steps.get_hash.outputs.hash }}
        with:
          script: |
            const hash = process.env.HASH;
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-ios-" + hash) {
                console.log('Clearing ' + cache.key + '...');
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                });
                console.log("Cache cleared.");
              }
            }
      - name: Uploading new cache
        uses: actions/cache@v3
        with:
          # caching again since for some reason it doesnt work with the first post cache shit
          key: cache-build-ios-${{ steps.get_hash.outputs.hash }}
          path: |
            .haxelib/
            ~/.hxcpp/
            export/release/ios/CodenameEngine/haxe/
            export/release/ios/CodenameEngine/obj/
          restore-keys: |
            cache-build-ios-${{ steps.get_hash.outputs.hash }}
